apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Frontend.serviceName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.Frontend.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.Frontend.containerPort }}
      targetPort: {{ .Values.Frontend.containerPort }}